spring:
  application:
    name: Todo 2025
  datasource:
    url: jdbc:h2:mem:tododb;MODE=MySQL
    driverClassName: org.h2.Driver
    username: ${usuario_bd}
    password:
    platform: h2

    h2:
      console:
        enabled: true

    jpa:
      database-platform: org.hibernate.dialect.MySQLDialect
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true

